# SPDX-License-Identifier: GPL-3.0-only
# SPDX-FileCopyrightText: 2023 Red Hat, Project Atmosphere
#
# Copyright 2023 Red Hat, Project Atmosphere
#
# This program is free software: you can redistribute it and/or modify it under the terms of the GNU
# General Public License as published by the Free Software Foundation, version 3 of the License.
#
# This program is distributed in the hope that it will be useful, but WITHOUT ANY WARRANTY; without
# even the implied warranty of MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.
# See the GNU General Public License for more details.
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#
# You should have received a copy of the GNU General Public License along with this program.
# If not, see <https://www.gnu.org/licenses/>.

---
namespace: sap

name: sap_operations

version: 1.14.2

readme: README.md

authors:
  - Ondra Machacek <omachace@redhat.com>
  - Kirill Satarin (@kksat)

description: Ansible collection to handle day 2 operational SAP administration tasks.

license:
  - GPL-3.0-only

tags:
  - linux
  - sap

dependencies: {}
repository: https://github.com/redhat-sap/rh_operations

documentation: https://github.com/redhat-sap/rh_operations

homepage: https://github.com/redhat-sap/rh_operations

issues: https://github.com/redhat-sap/rh_operations/issues

build_ignore:
  - roles/*/molecule
  - roles/*/tests
  - webdocs
  - docs
  - tests/output
  - .DS_Store
  - changelogs
  - changelogs-aap
  - changelogs-galaxy
  - __init__.py
  - plugins/__init__.py
  - plugins/doc_fragments/__init__.py
  - plugins/filter/__init__.py
  - plugins/module_utils/__init__.py
  - plugins/modules/__init__.py
  - plugins/test/__init__.py
  - galaxy-aap.yml
  - galaxy-galaxy.yml

  - plugins/module_utils/azure.py
  - plugins/modules/azure_imds.py

  - plugins/doc_fragments/community.py
  - plugins/doc_fragments/experimental.py

  - plugins/module_utils/pacemaker.py

  - plugins/modules/pcs_capabilities_info.py
  - plugins/modules/pcs_status_info.py
  - plugins/modules/pcs_cib_info.py
  - plugins/modules/pcs_fence_azure_arm_list_info.py
  - plugins/filter/pcs_cluster_property_mapping.py
  - plugins/filter/pcs_resources.py
  - plugins/filter/pcs_resources_from_cib.py
  - plugins/filter/pcs_resources_from_status.py
  - plugins/filter/all.py
  - plugins/filter/any.py
  - plugins/test/all.py
  - plugins/test/any.py

  - plugins/filter/license_content.py
  - plugins/modules/saplikey_get_info.py
  - plugins/modules/saplikey.py
  - plugins/modules/saplikey_show_info.py
  - plugins/module_utils/saplikey.py
  - plugins/doc_fragments/saplikey_common.py

  - plugins/action/me_downloadbasket_info.py
  - plugins/action/me_downloaditemset_info.py
  - plugins/action/me_file_info.py
  - plugins/filter/me_enr_from_alias.py
  - plugins/filter/mount_path.py
  - plugins/module_utils/me_auth.py
  - plugins/module_utils/me_constants.py
  - plugins/module_utils/me_helpers.py
  - plugins/modules/me_downloadbasket_info.py
  - plugins/modules/me_downloaditemset_info.py
  - plugins/modules/me_file_info.py
  - plugins/test/me_valid_alias.py

  - roles/pcs_config_checks
  - roles/pcs_group_check
  - plugins/filter/combine_default.py

  - plugins/modules/hana_restore.py

  - tests/sanity-ignore-galaxy
  - tests/sanity-ignore-aap

  - plugins/modules/abap_transport_create.py
  - plugins/modules/abap_transport_info.py
  - plugins/modules/abap_transport_import.py
  - plugins/modules/abap_transports_info.py

  - roles/hana/*

  - README-galaxy.md
  - README-aap.md
