# SPDX-License-Identifier: GPL-3.0-only
# SPDX-FileCopyrightText: 2023 Kirill Satarin (@kksat)
#
# Copyright 2023 Kirill Satarin (@kksat)
#
# This program is free software: you can redistribute it and/or modify it under the terms of the GNU
# General Public License as published by the Free Software Foundation, version 3 of the License.
#
# This program is distributed in the hope that it will be useful, but WITHOUT ANY WARRANTY; without
# even the implied warranty of MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.
# See the GNU General Public License for more details.
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#
# You should have received a copy of the GNU General Public License along with this program.
# If not, see <https://www.gnu.org/licenses/>.

---
# see documentation https://docs.ansible.com/ansible/latest/dev_guide/developing_program_flow_modules.html#argument-spec
# https://docs.ansible.com/ansible/latest/collections/ansible/builtin/validate_argument_spec_module.html

argument_specs:
  main:
    short_description: Manage SAP HANA instance
    description:
      - Manage SAP HANA instance
      - Role will not do anything is there is an instance already installed with SID=hana_sid or hana_instance_number is already occupied

    options:
      hana_state:
        description:
          - Defines if SAP HANA has to be installed or uninstalled.
        type: str
        required: false
        choices:
          - present
          - absent
        default: present

      hana_medium:
        description:
          - Location of Installation Medium
        type: path
        required: true

      hana_master_password:
        description:
          - SAP HANA master password.
          - Master password is not required when all other passwords are set.
          - If any other password is not set it will default to master password.
        type: str
        required: false

      hana_password:
        description:
          - System Administrator Password (<sid>adm). If not set will default to hana_master_password variable.
        type: str
        required: false

      hana_sapadm_password:
        description:
          - SAP Host Agent User (sapadm) password. If not set will default to hana_master_password variable.
        type: str
        required: false

      hana_system_user_password:
        description:
          - Database User Password. If not set will default to hana_master_password variable.
        type: str
        required: false

      hana_root_password:
        description: Root User Password For Remote Hosts. If not set will default to hana_master_password variable.
        type: str
        required: false

      hana_sid:
        description: SAP HANA SID
        type: str
        required: true

      hana_instance_number:
        description: SAP HANA instance number
        type: str
        required: false

  __limitations__:
    options: {}
    short_description: Limitations
    description:
      - Role was tested only on single host.

  __dependencies__:
    options: {}
    short_description: Dependencies
    description:
      - Role has no dependencies to other roles.

  __license__:
    options: {}
    short_description: License
    description:
      - GPL-3.0-only

  __author__:
    options: {}
    short_description: Author Information
    description:
      - Kirill Satarin (@kksat)
