---
# SPDX-License-Identifier: GPL-3.0-only
# SPDX-FileCopyrightText: 2024 Kirill Satarin (@kksat)
#
# Copyright 2024 Kirill Satarin (@kksat)
#
# This program is free software: you can redistribute it and/or modify it under the terms of the GNU
# General Public License as published by the Free Software Foundation, version 3 of the License.
#
# This program is distributed in the hope that it will be useful, but WITHOUT ANY WARRANTY; without
# even the implied warranty of MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.
# See the GNU General Public License for more details.
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#
# You should have received a copy of the GNU General Public License along with this program.
# If not, see <https://www.gnu.org/licenses/>.

- name: Fail if role is called directly
  ansible.builtin.fail:
    msg: This role should only be called from certain roles, see role documentation
  when:
    - not sapinst_allow_direct_usage
    - (ansible_parent_role_names is not defined) or ((ansible_parent_role_names | first) not in sapinst_allowed_parent_role_names)

- name: Make sure installation temp dir exists
  ansible.builtin.tempfile:
    path: "{{ sapinst_directory_path }}"
    prefix: "{{ sapinst_prefix }}."
    suffix: ".{{ sapinst_suffix }}"
    state: directory
  register: sapinst_directory

- name: Set required permissions for sapinst_directory
  ansible.builtin.file:
    path: "{{ sapinst_directory.path }}"
    owner: "{{ omit }}"
    group: sapinst
    mode: "0770"

- name: Make sure inifile.params created
  ansible.builtin.copy:
    dest: "{{ [sapinst_directory.path, 'inifile.params'] | ansible.builtin.path_join }}"
    content: "{{ sapinst_params | sap.sap_operations.inifile_params }}"
    owner: "{{ omit }}"
    group: "{{ omit }}"
    mode: "0400"

- name: Run sapinst command
  ansible.builtin.command:
    cmd: >
      {{ [sapinst_folder, 'sapinst'] | ansible.builtin.path_join }}
      SAPINST_INPUT_PARAMETERS_URL={{ [sapinst_directory.path, 'inifile.params'] | ansible.builtin.path_join }}
      SAPINST_EXECUTE_PRODUCT_ID={{ sapinst_product_id }}
      SAPINST_SKIP_DIALOGS=true
      SAPINST_SKIP_ERRORSTEP={{ sapinst_skip_errorstep }}
      SAPINST_MESSAGE_CONSOLE_THRESHOLD={{ sapinst_message_console_threshold }}
      -nogui
      -noguiserver
  become: true
  become_user: root
  changed_when: sapinst_command.rc == 0
  failed_when: sapinst_command.rc != 0
  register: sapinst_command

- name: Fail if installationSuccessfullyFinished.dat file does not exists
  ansible.builtin.stat:
    path: "{{ [sapinst_directory.path, 'installationSuccessfullyFinished.dat'] | ansible.builtin.path_join }}"
  register: sapinst_installation_successfully_finished
  failed_when: not sapinst_installation_successfully_finished.stat.exists
  when: sapinst_product_id != 'download_service_toplevel:GENERIC.IND.PD'
