---
# SPDX-License-Identifier: GPL-3.0-only
# SPDX-FileCopyrightText: 2023 Red Hat, Project Atmosphere
#
# Copyright 2023 Red Hat, Project Atmosphere
#
# This program is free software: you can redistribute it and/or modify it under the terms of the GNU
# General Public License as published by the Free Software Foundation, version 3 of the License.
#
# This program is distributed in the hope that it will be useful, but WITHOUT ANY WARRANTY; without
# even the implied warranty of MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.
# See the GNU General Public License for more details.
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#
# You should have received a copy of the GNU General Public License along with this program.
# If not, see <https://www.gnu.org/licenses/>.

- name: Make sure that unpack destination for SAP cloud connector exists
  ansible.builtin.file:
    path: "{{ cloudconnector_unpack_destination }}"
    state: directory
    mode: "0755"
    owner: "{{ omit }}"
    group: "{{ omit }}"

- name: Unpack downloaded RPM
  ansible.builtin.unarchive:
    remote_src: true
    list_files: true
    src: "{{ cloudconnector_download_filepath }}"
    dest: "{{ cloudconnector_unpack_destination }}"
    mode: "0755"
  register: __cloudconnector_unpack
  failed_when: __cloudconnector_unpack.files | length > 1

- name: Install SAP Cloud Connector RPM
  ansible.builtin.yum:
    name: "{{ cloudconnector_unpack_destination }}/{{ __cloudconnector_unpack.files | first }}"
    state: present
    disable_gpg_check: true
  become: true
  become_user: root
