# SPDX-License-Identifier: GPL-3.0-only
# SPDX-FileCopyrightText: 2024 Red Hat, Project Atmosphere
#
# Copyright 2024 Red Hat, Project Atmosphere
#
# This program is free software: you can redistribute it and/or modify it under the terms of the GNU
# General Public License as published by the Free Software Foundation, version 3 of the License.
#
# This program is distributed in the hope that it will be useful, but WITHOUT ANY WARRANTY; without
# even the implied warranty of MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.
# See the GNU General Public License for more details.
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#
# You should have received a copy of the GNU General Public License along with this program.
# If not, see <https://www.gnu.org/licenses/>.

---
- name: Make sure SAP HANA is downloaded and installed
  hosts: all
  gather_facts: false
  # vars:
  #   hana_sid: HAN
  #   hana_instance_number: "00"
  #   hana_master_password: "{{ lookup('ansible.builtin.env','SAP_OPERATIONS_HANA_MASTER_PASSWORD')}}"
  #   hana_version: "SPS07"
  #   hana_download_destination: /hana/software/downloaded/
  #   hana_unpack_destination: "/hana/software/unpacked/SAPHANA{{ hana_version }}"
  #   sap_operations_download_username: "{{ lookup('ansible.builtin.env','SAP_OPERATIONS_DOWNLOAD_USERNAME')}}"
  #   sap_operations_download_password: "{{ lookup('ansible.builtin.env','SAP_OPERATIONS_DOWNLOAD_PASSWORD')}}"
  tasks:
    - name: Validate that all required variables are set
      ansible.builtin.validate_argument_spec:
        argument_spec:
          DOCUMENTATION:
            required: false
            description:
              - This playbook will download and install SAP HANA server (database only, only one component)
              - This playbook assumes that hosts it is running against are prepared for SAP HANA installation
              - This playbook assumes that there is sufficient space on the host to download, unpack and install SAP HANA
              - This playbook assumes that folders /usr/sap and /hana exist and writable
              - See required parameters below
              - See sample values for parameters above
              - See how this playbook can be used directly https://docs.ansible.com/ansible/latest/collections/ansible/builtin/import_playbook_module.html
          hana_sid:
            required: true
            description:
              - SAP HANA system id
              - Must be correct SAP sid
          hana_instance_number:
            required: true
            description:
              - SAP HANA instance number
              - Must be number not less than zero and below 99
          hana_master_password:
            required: true
            description: SAP HANA master password, see role hana
          hana_version:
            required: true
            description: SAP HANA version, must be either 'SPSNN' or 'N.NNN.NN.NN' or 'N.NNN.NN.N', where N is digit
          hana_download_destination:
            required: true
            type: path
            description: Path where SAP HANA server binaries will be downloaded, will be created
          sap_operations_download_password:
            required: true
            description: SAP for me password
          sap_operations_download_username:
            required: true
            description: SAP for me username

    - name: Validate sid and instance number are correct
      ansible.builtin.assert:
        that:
          - hana_sid is sap.sap_operations.valid_sid
          - hana_instance_number | int >=0
          - hana_instance_number | int <=98
          - >-
            hana_version is ansible.builtin.regex("^SPS\d{2}$")
            or
            hana_version is ansible.builtin.regex("^\d\.\d{2}\.\d{3}\.\d{1,2}$")

    - name: Make sure hana_download_destination exists
      ansible.builtin.file:
        recurse: true
        name: "{{ hana_download_destination }}"
        state: directory
        mode: "0777"

    - name: Make sure sapcar exe is installed
      ansible.builtin.include_role:
        name: sap.sap_operations.sapcar

    - name: Make sure SAP HANA database binaries are downloaded
      ansible.builtin.include_role:
        name: sap.sap_operations.download
      vars:
        download_alias: hana-server
        download_description: "{{ hana_version }}"
        download_destination: "{{ hana_download_destination }}"

    - name: Unpack SAP HANA binaries
      ansible.builtin.include_role:
        name: sap.sap_operations.unpack
      vars:
        unpack_source: "{{ download_register_last.files | map(attribute='filepath') }}"
        unpack_destination: "{{ hana_unpack_destination }}"

    - name: Make sure SAP HANA is present
      ansible.builtin.include_role:
        name: sap.sap_operations.hana
      vars:
        hana_state: present
        hana_medium: "{{ hana_unpack_destination }}"
